# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

ff_C <- function(x) {
    .Call(`_CRFutilRcppComponents_ff_C`, x)
}

fix_node_and_edge_par <- function(node_par, edge_par) {
    .Call(`_CRFutilRcppComponents_fix_node_and_edge_par`, node_par, edge_par)
}

row_match <- function(x, table) {
    .Call(`_CRFutilRcppComponents_row_match`, x, table)
}

phi_features_C <- function(config, edge_mat, node_par, edge_par, num_params_default = 0L) {
    .Call(`_CRFutilRcppComponents_phi_features_C`, config, edge_mat, node_par, edge_par, num_params_default)
}

compute_model_matrix <- function(configs, edge_mat, node_par, edge_par, num_params_default = 0L) {
    .Call(`_CRFutilRcppComponents_compute_model_matrix`, configs, edge_mat, node_par, edge_par, num_params_default)
}

get_par_off <- function(config, i_in = NULL, j_in = NULL, node_par_in = NULL, edge_par_in = NULL, edge_mat_in = NULL, printQ = FALSE) {
    .Call(`_CRFutilRcppComponents_get_par_off`, config, i_in, j_in, node_par_in, edge_par_in, edge_mat_in, printQ)
}

phi_component <- function(config, i_in = NULL, j_in = NULL, node_par_in = NULL, edge_par_in = NULL, edge_mat_in = NULL) {
    .Call(`_CRFutilRcppComponents_phi_component`, config, i_in, j_in, node_par_in, edge_par_in, edge_mat_in)
}

symbolic_conditional_energy <- function(config, condition_element_number, edge_mat, node_par, edge_par, num_params_default = 0L) {
    .Call(`_CRFutilRcppComponents_symbolic_conditional_energy`, config, condition_element_number, edge_mat, node_par, edge_par, num_params_default)
}

