# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

ff_C <- function(x) {
    .Call(`_CRFutilRcppComponents_ff_C`, x)
}

fix_node_and_edge_par <- function(node_par, edge_par) {
    .Call(`_CRFutilRcppComponents_fix_node_and_edge_par`, node_par, edge_par)
}

row_match <- function(x, table) {
    .Call(`_CRFutilRcppComponents_row_match`, x, table)
}

get_num_params <- function(node_par, edge_par) {
    .Call(`_CRFutilRcppComponents_get_num_params`, node_par, edge_par)
}

phi_features_C <- function(config, edge_mat, node_par, edge_par, num_params_in = 0L) {
    .Call(`_CRFutilRcppComponents_phi_features_C`, config, edge_mat, node_par, edge_par, num_params_in)
}

compute_model_matrix <- function(configs, edge_mat, node_par, edge_par, num_params_in = 0L) {
    .Call(`_CRFutilRcppComponents_compute_model_matrix`, configs, edge_mat, node_par, edge_par, num_params_in)
}

get_par_off <- function(config, i_in, j_in, node_par_in, edge_par_in, edge_mat_in, printQ = FALSE) {
    .Call(`_CRFutilRcppComponents_get_par_off`, config, i_in, j_in, node_par_in, edge_par_in, edge_mat_in, printQ)
}

phi_component <- function(config, i_in, j_in, node_par_in, edge_par_in, edge_mat_in) {
    .Call(`_CRFutilRcppComponents_phi_component`, config, i_in, j_in, node_par_in, edge_par_in, edge_mat_in)
}

alpha_vector <- function(config, condition_element_number, edge_mat, node_par, edge_par, adj_nodes, num_params_in = 0L) {
    .Call(`_CRFutilRcppComponents_alpha_vector`, config, condition_element_number, edge_mat, node_par, edge_par, adj_nodes, num_params_in)
}

delta_alpha <- function(samples, node_par, edge_par, edge_mat, adj_nodes, num_params_in = 0L) {
    .Call(`_CRFutilRcppComponents_delta_alpha`, samples, node_par, edge_par, edge_mat, adj_nodes, num_params_in)
}

testemptymat <- function(emptymat) {
    invisible(.Call(`_CRFutilRcppComponents_testemptymat`, emptymat))
}

testslicedetect <- function(amat) {
    invisible(.Call(`_CRFutilRcppComponents_testslicedetect`, amat))
}

testslicedetect2 <- function(amat) {
    invisible(.Call(`_CRFutilRcppComponents_testslicedetect2`, amat))
}

testslicedetect3 <- function(amat) {
    .Call(`_CRFutilRcppComponents_testslicedetect3`, amat)
}

testslicedetect4 <- function(amat) {
    invisible(.Call(`_CRFutilRcppComponents_testslicedetect4`, amat))
}

testslicedetect5 <- function(amat) {
    invisible(.Call(`_CRFutilRcppComponents_testslicedetect5`, amat))
}

